import { useEffect, useState } from 'react'
import { ArrowRight, Atom, BookOpen, ChevronRight, CircuitBoard, Plane, Sigma } from 'lucide-react'
import { Link, Route, Routes, useParams } from 'react-router-dom'
import { type Department, type Faculty, getDirectory, getStats } from './data'

const icons = { plane: Plane, circuit: CircuitBoard, sigma: Sigma, atom: Atom }

function Header() { return <header><Link className="brand" to="/" aria-label="AFIT Digital Library home"><img src="/afit-logo.svg" alt="AFIT"/><span><b>AFIT</b><small>Digital Library</small></span></Link><nav aria-label="Primary navigation"><Link to="/">Home</Link><Link to="/departments">Departments</Link></nav></header> }
function Footer() { return <footer><div className="footer-brand"><img src="/afit-logo.svg" alt=""/><b>AFIT Digital Library</b></div><div><strong>Contact</strong><p>[PLACEHOLDER — replace with approved AFIT contact details]</p></div><div><strong>Follow AFIT</strong><p>[PLACEHOLDER — add verified AFIT social links]</p></div></footer> }
function Stats() {
  const [state, setState] = useState<{ facultyCount: number; departmentCount: number; preview: boolean } | null>(null)
  useEffect(() => { getStats().then(setState).catch(() => setState({ facultyCount: 0, departmentCount: 0, preview: false })) }, [])
  if (!state) return <div className="stats loading" aria-label="Loading library statistics"><i/><i/></div>
  return <div className="stats"><div><b>{state.facultyCount}</b><span>Faculties</span></div><div><b>{state.departmentCount}</b><span>Departments</span></div>{state.preview && <em>Preview counts — connect Supabase for live data</em>}</div>
}
function Home() { return <><Header/><main><section className="hero"><div className="eyebrow">Academic discovery · research · knowledge</div><h1>Quest for <i>Excellence</i></h1><p>[PLACEHOLDER — replace with real AFIT content] A focused starting point for finding the library resources that support your work.</p><Link className="button" to="/departments">Explore departments <ArrowRight size={18}/></Link><Stats/></section><section className="intro"><BookOpen size={26}/><div><span className="eyebrow">Your library, organised</span><h2>Find a collection by faculty</h2><p>Browse the departments and their subject collections from one accessible directory.</p></div><Link className="text-link" to="/departments">View directory <ChevronRight size={18}/></Link></section></main><Footer/></> }
function DepartmentCard({ department }: { department: Department }) { const Icon = icons[department.icon as keyof typeof icons] ?? BookOpen; return <Link className="department-card" to={`/departments/${department.slug}`} style={{ '--accent': department.color ?? '#1b5b70', '--image': department.background_image ? `url(${department.background_image})` : 'none' } as React.CSSProperties}><div className="card-image" aria-hidden="true"/><div className="card-content"><span className="card-icon"><Icon size={23}/></span><h3>{department.name}</h3><p>{department.description || '[PLACEHOLDER — replace with real AFIT content] Department library resources.'}</p><span className="card-link">View department <ArrowRight size={16}/></span></div></Link> }
function Skeletons() { return <div className="card-grid" aria-label="Loading departments">{[1,2,3,4,5,6].map(n => <div className="skeleton" key={n}><i/><b/><small/></div>)}</div> }
function Departments() {
  const [data, setData] = useState<{ faculties: Faculty[]; departments: Department[]; preview: boolean } | null>(null); const [error, setError] = useState(false); const [active, setActive] = useState('')
  useEffect(() => { getDirectory().then(result => { setData(result); setActive(result.faculties[0]?.id ?? '') }).catch(() => setError(true)) }, [])
  let content; if (error) content = <div className="notice error" role="alert"><h2>We couldn’t load the directory.</h2><p>Please check your connection and refresh the page.</p><button onClick={() => location.reload()}>Try again</button></div>; else if (!data) content = <Skeletons/>; else { const visible = data.departments.filter(d => d.faculty_id === active); content = <><div className="faculty-tabs" role="tablist" aria-label="Faculties">{data.faculties.map(f => <button key={f.id} role="tab" aria-selected={f.id === active} className={f.id === active ? 'selected' : ''} onClick={() => setActive(f.id)}>{f.name}</button>)}</div>{data.preview && <p className="preview-note">[PLACEHOLDER — preview directory data only. Connect Supabase for approved AFIT departments.]</p>}{visible.length ? <div className="card-grid">{visible.map(d => <DepartmentCard department={d} key={d.id}/>)}</div> : <div className="notice"><BookOpen size={30}/><h2>No visible departments yet</h2><p>This faculty does not currently have any departments available in the library directory.</p></div>}</> }
  return <><Header/><main className="directory"><div className="page-heading"><span className="eyebrow">Digital Library</span><h1>Explore departments</h1><p>Choose a faculty to browse its available department collections.</p></div>{content}</main><Footer/></>
}
function DepartmentDetail() { const { slug } = useParams(); return <><Header/><main className="detail"><span className="eyebrow">Department collection</span><h1>{slug?.split('-').map(x => x[0].toUpperCase()+x.slice(1)).join(' ')}</h1><p>[PLACEHOLDER — replace with real AFIT content] This department collection page is ready for approved AFIT resources and description.</p><Link className="text-link" to="/departments">← Back to departments</Link></main><Footer/></> }
export default function App() { return <Routes><Route path="/" element={<Home/>}/><Route path="/departments" element={<Departments/>}/><Route path="/departments/:slug" element={<DepartmentDetail/>}/></Routes> }
